Repository mongodb/leafygreen-ui, pull requests merged in 2022-11, with the labels that each got.

#1464 LG-2504, LG-2487, LG-2557: Refresh segmented control
  .changeset/olive-timers-film.md
  packages/segmented-control/src/SegmentedControl.spec.tsx
  packages/segmented-control/src/SegmentedControl.story.tsx
  packages/segmented-control/src/SegmentedControl.styles.ts
  packages/segmented-control/src/SegmentedControl.tsx
  packages/segmented-control/src/SegmentedControlContext.tsx
  packages/segmented-control/src/SegmentedControlOption.styles.ts
  packages/segmented-control/src/SegmentedControlOption.tsx
  packages/segmented-control/src/index.ts
  packages/segmented-control/src/types.ts
Labels: Dark Mode

#1479 LG-2502, LG-2488: Refresh code
  .changeset/shiny-flowers-wait.md
  packages/code/README.md
  packages/code/src/Code.story.tsx
  packages/code/src/Code.tsx
  packages/code/src/CopyButton.tsx
  packages/code/src/LanguageSwitcher.tsx
  packages/code/src/LanguageSwitcherExample.tsx
  packages/code/src/Panel.tsx
  packages/code/src/Syntax.tsx
  packages/code/src/WindowChrome.tsx
  packages/code/src/globalStyles.tsx
  packages/code/src/renderingPlugin.tsx
  packages/code/src/types.ts
Labels: Dark Mode

#1456 LG-2201: Group 4
  .changeset/mean-rules-sip.md
  .changeset/nice-bees-hope.md
  .changeset/olive-timers-film.md
  .changeset/pretty-comics-act.md
  .changeset/shiny-flowers-wait.md
  packages/code/README.md
  packages/code/src/Code.story.tsx
  packages/code/src/Code.tsx
  packages/code/src/CopyButton.tsx
  packages/code/src/LanguageSwitcher.tsx
  packages/code/src/LanguageSwitcherExample.tsx
  packages/code/src/Panel.tsx
  packages/code/src/Syntax.tsx
  packages/code/src/WindowChrome.tsx
  packages/code/src/globalStyles.tsx
  packages/code/src/renderingPlugin.tsx
  packages/code/src/types.ts
  packages/radio-box-group/package.json
  packages/radio-box-group/src/RadioBox.styles.ts
  packages/radio-box-group/src/RadioBox.tsx
  packages/radio-box-group/src/RadioBoxGroup.spec.tsx
  packages/radio-box-group/src/RadioBoxGroup.story.tsx
  packages/radio-box-group/src/RadioBoxGroup.styles.ts
  packages/radio-box-group/src/RadioBoxGroup.tsx
  packages/radio-box-group/src/Size.ts
  packages/radio-box-group/src/context.ts
  packages/radio-box-group/src/index.ts
  packages/radio-box-group/src/types.ts
  packages/radio-box-group/tsconfig.json
  packages/radio-group/package.json
  packages/radio-group/src/Radio.tsx
  packages/radio-group/src/RadioGroup.spec.tsx
  packages/radio-group/src/RadioGroup.story.tsx
  packages/radio-group/src/RadioGroup.tsx
  packages/radio-group/src/index.ts
  packages/radio-group/src/styles.ts
  packages/radio-group/src/types.ts
  packages/radio-group/tsconfig.json
  packages/segmented-control/package.json
  packages/segmented-control/src/SegmentedControl.story.tsx
  packages/segmented-control/src/SegmentedControl.styles.ts
  packages/segmented-control/src/SegmentedControl.tsx
  packages/segmented-control/src/SegmentedControlContext.tsx
  packages/segmented-control/src/SegmentedControlOption.styles.ts
  packages/segmented-control/src/SegmentedControlOption.tsx
  packages/segmented-control/src/index.ts
  packages/segmented-control/src/types.ts
  packages/segmented-control/tsconfig.json
  packages/toggle/package.json
  packages/toggle/src/Toggle.story.tsx
  packages/toggle/src/Toggle.tsx
  packages/toggle/src/index.ts
  packages/toggle/src/styles.ts
  packages/toggle/src/types.ts
  packages/toggle/tsconfig.json
  website/pages/component/radio-box-group/example.tsx
Labels: Dark Mode

#1505 Badge reorganization
  .changeset/pretty-apricots-develop.md
  packages/badge/src/Badge.story.tsx
  packages/badge/src/Badge/Badge.spec.tsx
  packages/badge/src/Badge/Badge.tsx
  packages/badge/src/Badge/styles.ts
  packages/badge/src/Badge/types.ts
  packages/badge/src/index.ts
  packages/badge/src/types.ts
Labels: Patch Version, Badge

#1508 LG-2555: Refresh table
  .changeset/funny-grapes-itch.md
  packages/table/package.json
  packages/table/src/Cell.tsx
  packages/table/src/NestedRow.tsx
  packages/table/src/Row.tsx
  packages/table/src/Table.tsx
  packages/table/src/TableHeader.tsx
  packages/table/src/styles.tsx
  packages/table/tsconfig.json
Labels: Dark Mode

#1495 LG-2553: Refresh confirmation modal
  .changeset/lucky-boats-add.md
  packages/confirmation-modal/package.json
  packages/confirmation-modal/src/ConfirmationModal.story.tsx
  packages/confirmation-modal/src/ConfirmationModal.styles.ts
  packages/confirmation-modal/src/ConfirmationModal.tsx
  packages/confirmation-modal/src/ConfirmationModal.types.ts
  packages/confirmation-modal/src/index.ts
  packages/confirmation-modal/tsconfig.json
Labels: Dark Mode

#1506 Converts Typography package to use new directory/file structure
  .changeset/three-stingrays-switch.md
  packages/typography/src/Body/Body.tsx
  packages/typography/src/Body/Body.types.ts
  packages/typography/src/Description.tsx
  packages/typography/src/Description/Description.styles.ts
  packages/typography/src/Description/Description.tsx
  packages/typography/src/Description/Description.types.ts
  packages/typography/src/Disclaimer.tsx
  packages/typography/src/Disclaimer/Disclaimer.styles.ts
  packages/typography/src/Disclaimer/Disclaimer.tsx
  packages/typography/src/Disclaimer/Disclaimer.types.ts
  packages/typography/src/H1.tsx
  packages/typography/src/H1/H1.styles.ts
  packages/typography/src/H1/H1.tsx
  packages/typography/src/H1/H1.types.ts
  packages/typography/src/H2.tsx
  packages/typography/src/H2/H2.styles.ts
  packages/typography/src/H2/H2.tsx
  packages/typography/src/H2/H2.types.ts
  packages/typography/src/H3/H3.styles.ts
  packages/typography/src/H3/H3.tsx
  packages/typography/src/H3/H3.types.ts
  packages/typography/src/InlineCode.tsx
  packages/typography/src/InlineCode/InlineCode.styles.ts
  packages/typography/src/InlineCode/InlineCode.tsx
  packages/typography/src/InlineCode/InlineCode.types.ts
  packages/typography/src/InlineKeyCode.tsx
  packages/typography/src/InlineKeyCode/InlineKeyCode.styles.ts
  packages/typography/src/InlineKeyCode/InlineKeyCode.tsx
  packages/typography/src/InlineKeyCode/InlineKeyCode.types.ts
  packages/typography/src/Label.tsx
  packages/typography/src/Label/Label.styles.ts
  packages/typography/src/Label/Label.tsx
  packages/typography/src/Label/Label.types.ts
  packages/typography/src/Link.tsx
  packages/typography/src/Link/Link.spec.tsx
  packages/typography/src/Link/Link.styles.ts
  packages/typography/src/Link/Link.tsx
  packages/typography/src/Link/Link.types.ts
  packages/typography/src/Overline/Overline.styles.ts
  packages/typography/src/Overline/Overline.tsx
  packages/typography/src/Overline/Overline.types.ts
  packages/typography/src/Subtitle/Subtitle.styles.ts
  packages/typography/src/Subtitle/Subtitle.tsx
  packages/typography/src/Subtitle/Subtitle.types.ts
  packages/typography/src/index.ts
  packages/typography/src/styles.tsx
  packages/typography/src/utils/StaticWidthText.tsx
  packages/typography/src/utils/useUpdatedBaseFontSize.ts
  packages/typography/tsconfig.json
  tsconfig.json
Labels: Patch Version, Typography

#1491 LG-2554: Refresh modal
  .changeset/lucky-boats-add.md
  .changeset/short-carrots-search.md
  packages/confirmation-modal/package.json
  packages/confirmation-modal/src/ConfirmationModal.story.tsx
  packages/confirmation-modal/src/ConfirmationModal.tsx
  packages/confirmation-modal/src/ConfirmationModal/ConfirmationModal.spec.tsx
  packages/confirmation-modal/src/ConfirmationModal/ConfirmationModal.tsx
  packages/confirmation-modal/src/ConfirmationModal/styles.ts
  packages/confirmation-modal/src/ConfirmationModal/types.ts
  packages/confirmation-modal/src/index.ts
  packages/confirmation-modal/tsconfig.json
  packages/modal/package.json
  packages/modal/src/Footer.tsx
  packages/modal/src/Footer/Footer.spec.tsx
  packages/modal/src/Footer/Footer.tsx
  packages/modal/src/Footer/styles.ts
  packages/modal/src/Footer/types.ts
  packages/modal/src/Modal.story.tsx
  packages/modal/src/Modal.tsx
  packages/modal/src/Modal/Modal.spec.tsx
  packages/modal/src/Modal/Modal.tsx
  packages/modal/src/Modal/ModalView.tsx
  packages/modal/src/Modal/styles.ts
  packages/modal/src/Modal/types.ts
  packages/modal/src/ModalView.tsx
  packages/modal/src/index.ts
Labels: Dark Mode

#1507 Banner reorganization
  .changeset/ten-suits-run.md
  packages/banner/src/Banner.story.tsx
  packages/banner/src/Banner/Banner.spec.tsx
  packages/banner/src/Banner/Banner.tsx
  packages/banner/src/Banner/styles.ts
  packages/banner/src/Banner/types.ts
  packages/banner/src/BannerDismissButton/BannerDismissButton.tsx
  packages/banner/src/BannerDismissButton/index.ts
  packages/banner/src/BannerDismissButton/styles.ts
  packages/banner/src/BannerDismissButton/types.ts
  packages/banner/src/BannerIcon/BannerIcon.tsx
  packages/banner/src/BannerIcon/index.ts
  packages/banner/src/BannerIcon/styles.ts
  packages/banner/src/BannerIcon/types.ts
  packages/banner/src/index.ts
  packages/banner/src/styles.ts
Labels: Patch Version, Banner
