Repository mongodb/leafygreen-ui, pull requests merged in 2022-04, with the labels that each got.

#1195 Bump yarn lock
  common.tsconfig.json
  packages/box/src/Box.tsx
  packages/button/src/Button.tsx
  packages/code/src/Syntax.tsx
  packages/code/src/languages.ts
  packages/code/src/renderingPlugin.tsx
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxOption.tsx
  packages/hooks/src/useForwardedRef.tsx
  packages/hooks/src/useValidation.tsx
  packages/icon/src/Icon.spec.tsx
  packages/icon/src/createIconComponent.tsx
  packages/icon/src/template.ts
  packages/leafygreen-provider/src/UsingKeyboardContext.spec.tsx
  packages/lib/src/index.ts
  packages/logo/src/Logo.story.tsx
  packages/logo/src/utils.ts
  packages/marketing-modal/src/blobs.tsx
  packages/menu/src/SubMenu.tsx
  packages/modal/src/Modal.spec.tsx
  packages/pipeline/src/Counter.tsx
  packages/pipeline/src/Stage.spec.tsx
  packages/popover/src/positionUtils.ts
  packages/radio-box-group/src/RadioBoxGroup.spec.tsx
  packages/radio-group/src/RadioGroup.tsx
  packages/ripple/src/Ripple.spec.tsx
  packages/ripple/src/getRippleGlobal.spec.tsx
  packages/ripple/src/getRippleGlobalNamespace.ts
  packages/segmented-control/src/SegmentedControl.tsx
  packages/select/src/ListMenu.tsx
  packages/select/src/Select.tsx
  packages/select/src/utils.tsx
  packages/side-nav/src/SideNav.tsx
  packages/side-nav/src/SideNavGroup.spec.tsx
  packages/stepper/src/Stepper.tsx
  packages/table/src/Row.tsx
  packages/table/src/Table.tsx
  packages/testing-lib/src/context.ts
  packages/testing-lib/src/jest.ts
  packages/text-area/src/TextArea.tsx
  packages/text-input/src/TextInput.story.tsx
  packages/toggle/src/Toggle.tsx
  packages/tokens/src/Tokens.story.tsx
  tsconfig.json
  website/components/CodeDocs.tsx
  website/components/live-example/LiveExample.tsx
  website/components/navigation/MobileNavigation.tsx
  website/layouts/BaseLayout.tsx
  website/pages/component/tokens/example.tsx
  yarn.lock
Labels: dependencies

#1200 PD-1915: createUniqueClassName Prefix
  .changeset/funny-wasps-share.md
  packages/lib/src/createUniqueClassName/createUniqueClassName.spec.ts
  packages/lib/src/createUniqueClassName/index.ts
Labels: Quick Review

#1181 Design website updates
  website/.babelrc
  website/components/CodeDocs.tsx
  website/components/PropTable.tsx
  website/components/live-example/Knobs.tsx
  website/components/live-example/LiveExample.tsx
  website/layouts/BaseLayout.tsx
  website/layouts/Footer.tsx
  website/next-env.d.ts
  website/next.config.js
  website/package.json
  website/pages/_app.tsx
  website/pages/component/badge/guidelines.mdx
  website/pages/component/badge/guidelines.tsx
  website/pages/component/banner/example.tsx
  website/pages/component/banner/guidelines.mdx
  website/pages/component/button/example.tsx
  website/pages/component/callout/example.tsx
  website/pages/component/callout/guidelines.mdx
  website/pages/component/code/example.tsx
  website/pages/component/code/guidelines.mdx
  website/pages/component/confirmation-modal/guidelines.mdx
  website/pages/component/form-footer/guidelines.mdx
  website/pages/component/icon/guidelines.mdx
  website/pages/component/marketing-modal/guidelines.mdx
  website/pages/component/menu/guidelines.mdx
  website/pages/component/segmented-control/guidelines.mdx
  website/pages/component/side-nav/guidelines.mdx
  website/pages/component/table/guidelines.mdx
  website/pages/component/text-input/guidelines.mdx
  website/pages/component/toast/example.tsx
  website/pages/component/toast/guidelines.mdx
  website/pages/component/tooltip/guidelines.mdx
  website/pages/component/typography/guidelines.mdx
  website/pages/foundation/accessibility.mdx
  website/pages/foundation/forms.mdx
  website/public/connect.svg
  website/styles/globals.tsx
  website/tsconfig.json
  website/utils/markdownToHtml.ts
  yarn.lock
Labels: website

#1204 Fixes typography bug
  .changeset/dry-waves-destroy.md
  packages/tokens/src/fontFamilies.ts
  packages/tokens/src/typeScales.ts
  packages/typography/src/FormElements/Description.tsx
  packages/typography/src/FormElements/Label.tsx
Labels: Quick Review

#1140 PD-1684 - Improves package json script
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  README.md
  package.json
  scripts/publish-storybook.sh
  website/.babelrc
  website/package.json
  website/pages/component/badge/guidelines.mdx
  website/pages/component/banner/guidelines.mdx
  website/pages/component/callout/guidelines.mdx
  website/pages/component/code/guidelines.mdx
  website/pages/component/confirmation-modal/guidelines.mdx
  website/pages/component/form-footer/guidelines.mdx
  website/pages/component/icon/guidelines.mdx
  website/pages/component/marketing-modal/guidelines.mdx
  website/pages/component/menu/guidelines.mdx
  website/pages/component/side-nav/guidelines.mdx
  website/pages/component/table/guidelines.mdx
  website/pages/component/text-input/guidelines.mdx
  website/pages/component/toast/guidelines.mdx
  website/pages/component/tooltip/guidelines.mdx
  website/pages/component/typography/guidelines.mdx
  website/pages/foundation/forms.mdx
  yarn.lock
Labels: Tooling

#1203 PD-1467: 'as' prop bug with NextJS Links on MenuItems
  .changeset/green-hounds-vanish.md
  packages/menu/README.md
  packages/menu/src/Menu.tsx
  packages/menu/src/SubMenu.tsx
Labels: Menu, Quick Review

#1205 PD-1941 form elements font size fix
  .changeset/dull-countries-greet.md
  packages/typography/src/FormElements/Description.tsx
  packages/typography/src/FormElements/Label.tsx
  packages/typography/src/index.ts
  packages/typography/src/useUpdatedBaseFontSize.ts
Labels: Quick Review

#1148 Adds additional build script functionality
  scripts/build.js
  yarn.lock
Labels: Tooling

#1192 PD-1932 Dark mode button
  package.json
  packages/button/src/Button.story.tsx
  packages/button/src/Button.tsx
  packages/button/src/ButtonIcon.tsx
  packages/button/src/index.ts
  packages/button/src/styles.ts
  packages/button/src/types.ts
  website/pages/component/button/example.tsx
  yarn.lock
Labels: Dark Mode

#1206 PR Template: Add screenshot checkbox
  .github/pull_request_template.md
Labels: Quick Review

#1209 changing h3 font-weight to 600
  .changeset/happy-fishes-agree.md
  packages/typography/src/Typography.tsx
Labels: Quick Review

#1210 PD-1965: Expandable Card Styles + Dependencies
  .changeset/serious-readers-sing.md
  packages/expandable-card/package.json
  packages/expandable-card/src/ExpandableCard.tsx
Labels: Quick Review

#1194 PD-1939 Dark Mode text input & minor Button fixes
  .changeset/bright-kings-peel.md
  .changeset/short-trees-knock.md
  .changeset/six-comics-do.md
  packages/button/src/Button.tsx
  packages/button/src/styles.ts
  packages/text-input/src/TextInput.spec.tsx
  packages/text-input/src/TextInput.story.tsx
  packages/text-input/src/TextInput.tsx
  packages/text-input/src/index.ts
  packages/text-input/src/style.ts
  packages/text-input/src/types.ts
  packages/typography/src/Typography.tsx
  packages/typography/src/useUpdatedBaseFontSize.ts
  website/pages/component/code/guidelines.mdx
  website/pages/component/text-input/example.tsx
Labels: Dark Mode

#1216 PD-1913: Updating Figma links and adding missing component data
  website/utils/componentData.ts
Labels: Quick Review

#1222 PD-1960: Website - Adding variant knob to Confirmation Modal
  website/pages/component/confirmation-modal/example.tsx
Labels: Quick Review

#1221 PD-1965: Updating package versions on Expandable Card
  .changeset/unlucky-islands-joke.md
  packages/expandable-card/package.json
Labels: Quick Review

#1220 PD-1828: Updating package versions on Form Footer
  .changeset/khaki-cats-matter.md
  packages/form-footer/package.json
Labels: Quick Review

#1223 PD 1960: Website - Confirmation Modal variant knob build:ts fix
  website/pages/component/confirmation-modal/example.tsx
Labels: Quick Review

#1226 Updating stories for Badge, Button, Banner, Callout
  .storybook/preview.js
  packages/badge/src/Badge.story.jsx
  packages/banner/src/Banner.story.jsx
  packages/banner/src/Banner.story.tsx
  packages/button/src/Button.story.tsx
  packages/callout/src/Callout.story.jsx
  packages/callout/src/Callout.story.tsx
Labels: Quick Review, Docs Only

#1225 [PD-1985] menu aria attribute
  .changeset/healthy-grapes-fetch.md
  packages/menu/src/Menu.spec.tsx
  packages/menu/src/MenuItem.tsx
Labels: Quick Review

#1217 PD-1961: Moving leafygreen-provider to peerDependencies
  .changeset/bright-countries-help.md
  packages/checkbox/package.json
  packages/code/package.json
  packages/icon-button/package.json
  packages/interaction-ring/package.json
  packages/popover/package.json
  packages/segmented-control/package.json
  packages/tabs/package.json
Labels: Quick Review

#1230 PD-1993: Stories for Box, Card, Checkbox, Code
  .storybook/utils/IntrinsicElements.ts
  packages/box/src/Box.story.tsx
  packages/card/src/Card.story.tsx
  packages/card/src/Card.tsx
  packages/checkbox/src/Checkbox.story.tsx
  packages/code/src/Code.story.tsx
  stories/sample-pages/layout-1.stories.jsx
Labels: Docs Only

#1232 Modal provider dependency
  packages/modal/package.json
  packages/modal/tsconfig.json
Labels: Quick Review

#1233 PD-1677: update modal README to include a note about usePortal
  packages/modal/README.md
Labels: Quick Review
