Repository mongodb/leafygreen-ui, pull requests merged in 2022-06, with the labels that each got.

#1275 PD-1739 combobox single select menu behaviour (COMBOBOX #3)
  .changeset/fuzzy-walls-allow.md
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/utils/getDisplayNameForValue.ts
  packages/combobox/src/utils/index.ts
Labels: Combobox

#1280 PD-2045 Combobox input min-width fix (COMBOBOX #4)
  .changeset/rich-olives-confess.md
  packages/combobox/src/Combobox.story.tsx
  packages/combobox/src/Combobox.styles.ts
  packages/combobox/src/ComboboxOption.tsx
Labels: Quick Review, Combobox

#1288 PD-1801 Adds disabled combobox option prop (COMBOBOX #5)
  .changeset/red-scissors-protect.md
  .changeset/rich-trees-smile.md
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.story.tsx
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxOption.tsx
  packages/combobox/src/ComboboxTestUtils.tsx
  packages/combobox/src/utils/ComboboxUtils.spec.tsx
  packages/combobox/src/utils/OptionObjectUtils.ts
  packages/combobox/src/utils/flattenChildren.tsx
  packages/combobox/src/utils/index.ts
Labels: Combobox

#1290 PD-1771 Combobox sizes (COMBOBOX #6)
  .changeset/five-suits-serve.md
  packages/combobox/src/Chip.tsx
  packages/combobox/src/Combobox.story.tsx
  packages/combobox/src/Combobox.styles.ts
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxContext.tsx
Labels: Combobox

#1307 PD-2092: text input darkmode updates
  .changeset/wet-jeans-greet.md
  packages/text-input/package.json
  packages/text-input/src/style.ts
  packages/text-input/tsconfig.json
  yarn.lock
Labels: Quick Review

#1293 PD-2125 Refactor combobox css (#1)
  packages/combobox/src/Chip.tsx
  packages/combobox/src/Combobox.styles.ts
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxContext.tsx
  packages/combobox/src/ComboboxGroup.tsx
  packages/combobox/src/ComboboxOption.tsx
  packages/combobox/src/Menu.styles.ts
Labels: Combobox

#1297 PD-2125 Refactor combobox menu (#2)
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/ComboboxContext.tsx
  packages/combobox/src/ComboboxMenu/ComboboxMenu.tsx
  packages/combobox/src/ComboboxMenu/Menu.styles.ts
  packages/combobox/src/ComboboxOption.tsx
Labels: Combobox

#1306 PD-2012: Disclaimer style updates
  .changeset/modern-emus-happen.md
  packages/typography/src/Disclaimer.tsx
Labels: Quick Review

#1308 PD-2133: update refresh guideline href
  website/pages/foundation/refresh-guide.mdx
Labels: Quick Review

#1311 PD-2165: Refresh card
  .changeset/eighty-colts-draw.md
  packages/card/src/Card.tsx
Labels: Dark Mode

#1323 PD-2178: Textarea z-index
  .changeset/old-grapes-melt.md
  packages/text-area/src/styles.ts
Labels: Quick Review

#1328 PD-2153, PD-2042, PD-1899: Fix small content issues in .design
  website/pages/component/callout/guidelines.mdx
  website/pages/foundation/accessibility.mdx
  website/pages/foundation/forms.mdx
Labels: Docs Only

#1316 Pd 2030: Docs for lib
  .storybook/preview-head.html
  .storybook/preview.js
  packages/badge/src/Badge.story.tsx
  packages/banner/src/Banner.story.tsx
  packages/box/src/Box.story.tsx
  packages/button/src/Button.story.tsx
  packages/callout/src/Callout.story.tsx
  packages/card/src/Card.story.tsx
  packages/checkbox/src/Checkbox.story.tsx
  packages/code/src/Code.story.tsx
  packages/combobox/src/Combobox.story.tsx
  packages/confirmation-modal/src/ConfirmationModal.story.tsx
  packages/copyable/src/Copyable.story.tsx
  packages/expandable-card/src/ExpandableCard.story.tsx
  packages/form-footer/src/FormFooter.story.tsx
  packages/icon-button/src/IconButton.story.tsx
  packages/icon/src/Icon.story.tsx
  packages/inline-definition/src/InlineDefinition.story.tsx
  packages/leafygreen-provider/src/LeafyGreenContext.tsx
  packages/leafygreen-provider/src/TypographyContext.tsx
  packages/leafygreen-provider/src/leafygreen-provider.stories.tsx
  packages/lib/src/DarkModeProps/DarkModeProps.stories.mdx
  packages/lib/src/createUniqueClassName/createUniqueClassName.stories.mdx
  packages/lib/src/createUniqueClassName/index.ts
  packages/lib/src/getNodeTextContent/getNodeTextContent.stories.mdx
  packages/logo/src/Logo.story.tsx
  packages/marketing-modal/src/MarketingModal.story.tsx
  packages/menu/src/Menu.story.tsx
  packages/modal/src/Modal.story.tsx
  packages/palette/src/palette.story.tsx
  packages/pipeline/src/Pipeline.story.tsx
  packages/popover/src/Popover.story.tsx
  packages/portal/src/Portal.story.tsx
  packages/radio-box-group/src/RadioBoxGroup.story.tsx
  packages/radio-group/src/RadioGroup.story.tsx
  packages/segmented-control/src/SegmentedControl.story.tsx
  packages/select/src/Select.story.tsx
  packages/side-nav/src/SideNav.story.tsx
  packages/stepper/src/Stepper.story.tsx
  packages/table/src/Table.story.tsx
  packages/tabs/src/Tabs.story.tsx
  packages/text-area/src/TextArea.story.tsx
  packages/text-input/src/TextInput.story.tsx
  packages/toast/src/Toast.story.tsx
  packages/toggle/src/Toggle.story.tsx
  packages/tokens/src/Tokens.story.tsx
  packages/tooltip/src/Tooltip.story.tsx
  packages/typography/src/Typography.story.tsx
  scripts/package-builder.js
Labels: Docs Only

#1319 PD-2166: Refresh Copyable
  .changeset/nervous-deers-cheat.md
  packages/copyable/package.json
  packages/copyable/src/Copyable.tsx
Labels: Dark Mode

#1325 PD-2170: Refresh Tabs
  .changeset/nasty-turtles-type.md
  packages/tabs/src/TabTitle.tsx
  packages/tabs/src/Tabs.story.tsx
  packages/tabs/src/Tabs.tsx
Labels: Dark Mode

#1326 PD-1900 Select truncation
  .changeset/odd-ants-cheat.md
  packages/select/src/MenuButton.tsx
  packages/select/src/Select.story.tsx
Labels: Quick Review
