Repository mongodb/leafygreen-ui, pull requests merged in 2022-05, with the labels that each got.

#1238 Update Combobox Story CSF
  packages/combobox/src/Combobox.story.tsx
  packages/confirmation-modal/src/ConfirmationModal.story.tsx
  packages/copyable/src/Copyable.story.tsx
  packages/expandable-card/src/ExpandableCard.story.tsx
  packages/marketing-modal/src/MarketingModal.story.tsx
Labels: Quick Review, Docs Only

#1248 PD-1805 Update favicons
  .storybook/static/favicon.ico
  .storybook/static/logo.svg
  .storybook/theme.js
  website/public/favicon.ico
Labels: Quick Review

#1250 Deprecate Knobs: Modal
  packages/modal/src/Modal.story.tsx
Labels: Quick Review, Docs Only

#1253 Removing cursor:not-allowed on disabled Rows
  .changeset/purple-pillows-try.md
  packages/table/src/Row.tsx
Labels: Quick Review

#1247 Form components Design QA
  .storybook/preview-head.html
  packages/expandable-card/src/ExpandableCard.tsx
  packages/form-footer/src/FormFooter.tsx
Labels: Quick Review

#1258 PD-1988: Temp page for brand guidance on .design
  website/components/navigation/Navigation.tsx
  website/pages/foundation/refresh-guide.mdx
Labels: Quick Review, Docs Only

#1249 Updates to Combobox: PD-1991 (PD-2024, PD-2011, PD 1910, PD-1907, PD-1860)
  .changeset/gorgeous-scissors-explode.md
  .changeset/serious-poets-pull.md
  packages/combobox/README.md
  packages/combobox/src/Chip.tsx
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.story.tsx
  packages/combobox/src/Combobox.styles.ts
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxTestUtils.tsx
  packages/combobox/src/util.tsx
  website/pages/component/combobox/guidelines.mdx
Labels: Minor Version

#1261 PD-2063: parse-docs script
  package.json
  scripts/parse-tsdocs.js
Labels: Quick Review

#1268 Fixes Expandable Card TS build
  .changeset/silent-snails-invent.md
  packages/expandable-card/tsconfig.json
Labels: Quick Review

#1263 Storybook control fixes for Button and Tooltip
  .changeset/nervous-mirrors-join.md
  packages/button/src/Button.story.tsx
  packages/button/src/types.ts
  packages/tooltip/src/Tooltip.story.tsx
Labels: Quick Review

#1256 PD-2046 Combobox Backdrop Click
  .changeset/great-pets-do.md
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.tsx
Labels: Patch Version

#1279 Remove theme package
  build.tsconfig.json
  packages/pipeline/tsconfig.json
  packages/text-input/tsconfig.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
  packages/theme/src/colors.ts
  packages/theme/src/index.ts
  packages/theme/tsconfig.json
Labels: Quick Review

#1282 Remove theme from build tsconfig
  packages/badge/tsconfig.json
  packages/portal/tsconfig.json
  scripts/link.sh
Labels: Quick Review

#1281 Updating story filetypes and TSDocs
  packages/badge/src/Badge.story.jsx
  packages/badge/src/Badge.story.tsx
  packages/banner/src/Banner.story.jsx
  packages/banner/src/Banner.story.tsx
  packages/banner/src/Banner.tsx
  packages/box/src/Box.story.tsx
  packages/box/src/Box.tsx
  packages/button/src/Button.story.tsx
  packages/button/src/Button.tsx
  packages/button/src/types.ts
Labels: Quick Review, Docs Only

#1262 PD-2056: Palette TSDoc updates + parse-docs script change
  .changeset/fuzzy-goats-wash.md
  .gitignore
  packages/palette/src/index.ts
  packages/palette/src/palette.story.tsx
  packages/palette/src/palette.ts
  packages/palette/src/uiColors.ts
  scripts/parse-tsdocs.js
Labels: Quick Review

#1266 [PD-1737] Preserve Combobox focus when removing a chip
  .changeset/tiny-balloons-count.md
  packages/combobox/src/Chip.tsx
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.styles.ts
  packages/combobox/src/Combobox.tsx
  website/pages/foundation/refresh-guide.mdx
Labels: Combobox

#1283 PD-2064: Palette - gray dark 4
  .changeset/spotty-forks-march.md
  packages/palette/src/palette.less
  packages/palette/src/palette.spec.ts
  packages/palette/src/palette.ts
Labels: Quick Review

#1284 PD-2074: Changing disabled button icon color
  .changeset/warm-socks-occur.md
  packages/button/src/ButtonIcon.tsx
Labels: Quick Review

#1276 PD-2070 Extend keyMap and cleanup combobox dir (COMBOBOX #2)
  .changeset/small-years-cover.md
  .changeset/tiny-trains-float.md
  packages/combobox/src/Chip.tsx
  packages/combobox/src/Combobox.spec.tsx
  packages/combobox/src/Combobox.tsx
  packages/combobox/src/Combobox.types.ts
  packages/combobox/src/ComboboxOption.tsx
  packages/combobox/src/ComboboxTestUtils.tsx
  packages/combobox/src/util.tsx
  packages/combobox/src/utils/ComboboxUtils.spec.tsx
  packages/combobox/src/utils/flattenChildren.tsx
  packages/combobox/src/utils/getDisplayNameForValue.ts
  packages/combobox/src/utils/getNameAndValue.ts
  packages/combobox/src/utils/index.ts
  packages/combobox/src/utils/wrapJSX.tsx
  packages/lib/src/index.ts
  packages/palette/src/palette.less
  stories/Writing-Stories.stories.mdx
Labels: lib, Combobox
