Repository mongodb/leafygreen-ui, pull requests merged in 2023-02, with the labels that each got.

#1617 Styleguide additions
  STYLEGUIDE.md
Labels: Docs Only

#1639 LG-2919 fix pagination live example
  .changeset/breezy-dingos-deliver.md
  .changeset/fluffy-jobs-tickle.md
  packages/lib/src/storybook/StoryMeta.ts
  packages/pagination/src/Pagination.story.tsx
Labels: 2. Bug Fix 🪲

#1640 Removes sections from PR template
  .github/pull_request_template.md
Labels: 5. Docs only 📄

#1618 LG-2826: Don't filter out props being passed to Link component
  .changeset/little-ads-drum.md
  packages/typography/src/Link/Link.spec.tsx
  packages/typography/src/Link/Link.tsx
  packages/typography/src/Link/Link.types.ts
  packages/typography/src/Typography.story.tsx
Labels: 2. Bug Fix 🪲
