Repository mongodb/leafygreen-ui, pull requests merged in 2023-05, with the labels that each got.

#1734 LG-3159 search input focus
  .changeset/hungry-zebras-shake.md
  packages/search-input/src/SearchInput/SearchInput.spec.tsx
  packages/search-input/src/SearchInput/SearchInput.tsx
Labels: 2. Bug Fix 🪲

#1752 LG-3213: Allows null to be passed to SegmentedControl
  .changeset/nervous-geese-wink.md
  packages/segmented-control/src/SegmentedControl/SegmentedControl.tsx
Labels: 2. Bug Fix 🪲

#1673 Initial Chromatic setup
  .gitignore
  package.json
  packages/banner/src/Banner.story.tsx
  packages/hooks/src/useAutoScroll/useAutoScroll.story.tsx
  stories/ProviderDemo.story.tsx
  stories/forms/SampleForm.stories.tsx
  stories/sample-pages/layout-1.stories.jsx
  yarn.lock
Labels: 4. Tooling ⚒️

#1748 Lg-3175: Properly export Typography props and fix InlineCode prop definition
  .changeset/heavy-lamps-hope.md
  packages/typography/src/Body/Body.tsx
  packages/typography/src/Body/Body.types.ts
  packages/typography/src/Disclaimer/Disclaimer.tsx
  packages/typography/src/Error/Error.tsx
  packages/typography/src/Error/Error.types.ts
  packages/typography/src/H1/H1.tsx
  packages/typography/src/H1/H1.types.ts
  packages/typography/src/H2/H2.tsx
  packages/typography/src/H2/H2.types.ts
  packages/typography/src/H3/H3.tsx
  packages/typography/src/H3/H3.types.ts
  packages/typography/src/InlineCode/InlineCode.tsx
  packages/typography/src/InlineCode/InlineCode.types.ts
  packages/typography/src/Label/Label.tsx
  packages/typography/src/Label/Label.types.ts
  packages/typography/src/Link/Link.spec.tsx
  packages/typography/src/Link/Link.tsx
  packages/typography/src/Link/Link.types.ts
  packages/typography/src/Overline/Overline.tsx
  packages/typography/src/Overline/Overline.types.ts
  packages/typography/src/Subtitle/Subtitle.tsx
  packages/typography/src/Subtitle/Subtitle.types.ts
Labels: 1. New Feature 🚀

#1743 LG-3209: ToastProvider/useToast no longer forces rerender every time the stack changes
  .changeset/strong-onions-grow.md
  packages/toast/src/ToastContext/ToastProvider/ToastProvider.tsx
  packages/toast/src/ToastContext/ToastReducer/useToastReducer.ts
  packages/toast/src/ToastContext/useToast/useToast.spec.tsx
Labels: 2. Bug Fix 🪲

#1756 Chromatic CI [LG-3229]
  .github/workflows/nodejs.yml
  .storybook/preview-head.html
  packages/table/package.json
  packages/table/src/Cell/HeaderCell/HeaderCell.spec.tsx
  packages/table/src/Row/Row.stories.tsx
  packages/table/src/Table.story.tsx
  packages/table/src/TableHead/TableHead.stories.tsx
  packages/table/src/TableV10/Table.story.tsx
  packages/table/src/TableV10/fixtures.testutils.ts
  packages/table/src/TableV10/testUtils.tsx
  packages/table/src/TableWithVS.story.tsx
  packages/table/src/V11Adapter/V11Adapter.spec.tsx
  packages/table/src/V11Adapter/V11Adapter.story.tsx
  packages/table/src/utils/makeData.testutils.tsx
  packages/toast/package.json
  packages/toast/src/Toast.story.tsx
  scripts/depcheck.ts
  scripts/ts-build.ts
  yarn.lock
Labels: 4. Tooling ⚒️

#1758 LG-3034: Split button
  .changeset/hungry-balloons-explode.md
  .changeset/rare-moose-rest.md
  .changeset/rude-poets-shake.md
  .changeset/slimy-dragons-attend.md
  .changeset/ten-timers-share.md
  README.md
  build.tsconfig.json
  packages/button/README.md
  packages/lib/src/index.ts
  packages/lib/src/storybook/storybookExcludedControlParams.ts
  packages/menu/src/Menu/Menu.tsx
  packages/menu/src/Menu/Menu.types.ts
  packages/menu/src/MenuItem/MenuItem.tsx
  packages/split-button/README.md
  packages/split-button/package.json
  packages/split-button/src/Menu/Menu.styles.ts
  packages/split-button/src/Menu/Menu.tsx
  packages/split-button/src/Menu/Menu.types.ts
  packages/split-button/src/Menu/index.ts
  packages/split-button/src/SplitButton.story.tsx
  packages/split-button/src/SplitButton/SplitButton.spec.tsx
  packages/split-button/src/SplitButton/SplitButton.styles.ts
  packages/split-button/src/SplitButton/SplitButton.tsx
  packages/split-button/src/SplitButton/SplitButton.types.ts
  packages/split-button/src/SplitButton/index.tsx
  packages/split-button/src/index.ts
  packages/split-button/tsconfig.json
Labels: 1. New Feature 🚀
